title: Transmission mechanisms of plague cannot be uniquely identified from historical mortality data
description: Mechanistic models suggest that multiple transmission modes drove the Second Pandemic plague epidemics. Information from later epidemics improves resolution, but assumes similar biology.
theme: jekyll-theme-cayman